theme: jekyll-theme-leap-day

# Site settings
title: You Blog                     #你博客的标题
SEOTitle: Deeperss Blog        #显示在浏览器上搜索的时候显示的标题
header-img: img/post-bg-rwd.jpg     #显示在首页的背景图片
email: 645593673@qq.com    
description: "Do, not stay."              #网站介绍
keyword: "Deeperss" #关键词
url: "https://github.com/Deeperss.github.io"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写

# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页
